# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
    push:
        branches: ["main", "develop"]
    pull_request:
        branches: ["main", "develop"]

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v2

            - name: Restore NuGet packages
              run: nuget restore Doppler.sln

            - name: Build solution
              run: msbuild Doppler.sln /p:Configuration=Release
